language: node_js
node_js:
  - "10"
sudo: required
services:
  - docker

before_install:
  - docker build -t legan/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run legan/react-test npm test

after_success:
  - docker build -t legan/multi-client ./client
  - docker build -t legan/multi-nginx ./nginx
  - docker build -t legan/multi-server ./server
  - docker build -t legan/multi-worker ./worker

  # Log in to the Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Take those images and push them to Docker Hub
  - docker push legan/multi-client
  - docker push legan/multi-nginx
  - docker push legan/multi-server
  - docker push legan/multi-worker

deploy:
  provider: elasticbeanstalk
  region: eu-west-2
  app: "docker-react"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-eu-west-2-376311266098"
  bucker_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY