sudo: required
services:
  - docker

before_install:
  - docker build -t legan/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run legan/react-test npm test

after_success:
  - docker build -t legan/multi-client ./client
  - docker build -t legan/multi-nginx ./nginx
  - docker build -t legan/multi-server ./server
  - docker build -t legan/multi-worker ./worker

  # Log in to the Docker CLI
  - echo "DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Take those images and push them to Docker Hub
  - docker push legan/multi-client
  - docker push legan/multi-nginx
  - docker push legan/multi-server
  - docker push legan/multi-worker